name: Trigger Notice Update on a CRON Schedule

on:
  schedule:
    # Runs "at every 10 minute" (see https://crontab.guru)
    - cron: '*/1 * * * *'

jobs:
  build:
    name: Trigger Notice Update
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
#          curl -X GET ${{ secrets.NOTICE_URL }}/new \
#          -H "Authorization: Bearer ${{ secrets.KURING_API_KEY }}"
          curl -X GET ${{ secrets.NOTICE_URL }}