name: Trigger Notice Update on a CRON Schedule

on:
  schedule:
    # Runs "At every 10 minute" (see https://crontab.guru)
    - cron: '*/10 * * * *'

jobs:
  schedule:
    name: Trigger Notice Update
    runs-on: ubuntu-latest
    steps:
    - name: Dev cURL request
      env:
        URL: ${{ secrets.NOTICE_DEV_URL }}
        API_KEY: ${{ secrets.KURING_API_KEY }}
      run: |
          curl -X GET $URL/new \
          -H "Authorization: Bearer $API_KEY"

#    - name: Prod cURL request
#      env:
#        URL: ${{ secrets.NOTICE_PROD_URL }}
#        API_KEY: ${{ secrets.KURING_API_KEY }}
#      run: |
#        curl -X GET $URL/new \
#        -H "Authorization: Bearer $API_KEY"
