name: Trigger Staff Update on a CRON Schedule

on:
  schedule:
    # Runs "At 00:00 on day-of-month 14 and 28" (see https://crontab.guru)
    - cron: '30 1 14,28 * *'

jobs:
  schedule:
    name: Trigger Staff Update
    runs-on: ubuntu-latest
    steps:
    - name: Dev cURL request
      env:
        URL: ${{ secrets.STAFF_DEV_URL }}
        API_KEY: ${{ secrets.KURING_API_KEY }}
      run: |
        curl -X GET $URL/all \
        -H "Authorization: Bearer $API_KEY"

#    - name: Prod cURL request
#      env:
#        URL: ${{ secrets.STAFF_PROD_URL }}
#        API_KEY: ${{ secrets.KURING_API_KEY }}
#      run: |
#        curl -X GET $URL/all \
#        -H "Authorization: Bearer $API_KEY"
